version: '3.8'

services:
  app:
    build: .
    image: g2g-api-ollama
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API=http://ollama:11434
    volumes:
      - .:/app


  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
