version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  app:
    build: .
    image: g2g-ollama-app
    container_name: g2g-app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
       - DOCUMENTS_FOLDER=/app/uploaded_docs
    restart: unless-stopped

volumes:
  ollama_data: