name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.G2G_AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry (ACR)
      run: az acr login --name g2gdocker

    - name: Build and tag Docker image using docker-compose
      run: |
        docker-compose -f docker-compose.yml build app
        docker tag app g2gdocker.azurecr.io/g2gdockerimage:v1

    - name: Push Docker image to ACR
      run: |
        docker push g2gdocker.azurecr.io/g2gdockerimage:v1

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: g2g-be
        images: g2gdocker.azurecr.io/g2gdockerimage:v1
